[package]
name = "physics-and-tracing"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/zyx-db/rust-raytracing/tree/master"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.5"
rand = "*"
rayon = "*"
